### ISSUE TITLE
blog - All Categories

### ISSUE THREAD

**Issue by wightmike** [eflip/Blog#10]
![image](https://cloud.githubusercontent.com/assets/8368570/8866695/5e220476-318d-11e5-9f3a-37f2e4020385.png)

When viewing the main blog page, or by selecting "all categories" from the Categories sidebar, the "All Categories" tab should be class="active".

**Comment by bioshazard** [comment]
https://github.com/eflip/Blog/commit/4d44ff5427cf763576697319b38a133b35a1bb5b
