### ISSUE TITLE
blog - code cleanup (mvc)

### ISSUE THREAD

**Issue by wightmike** [eflip/Blog#11]
![image](https://cloud.githubusercontent.com/assets/8368570/8866714/97b773a6-318d-11e5-9f01-a29a94a852d4.png)

![image](https://cloud.githubusercontent.com/assets/8368570/8866739/d499f08c-318d-11e5-99c6-2fc3b07aa49b.png)

![image](https://cloud.githubusercontent.com/assets/8368570/8866746/f18c5540-318d-11e5-880b-ae68335dfef8.png)

There appears to be a lot of html where it shouldn't be. Is it possible to clean this sort of stuff up in blog at all?

**Comment by bioshazard** [comment]
https://github.com/eflip/Blog/pull/14
