### ISSUE TITLE
blog - save notice (success)

### ISSUE THREAD

**Issue by wightmike** [eflip/Blog#12]
![image](https://cloud.githubusercontent.com/assets/8368570/8866837/1e820ecc-318f-11e5-8f69-398dc6771955.png)

When an article is saved, we should be using a success notice to show that it is saved.

There should also be a link in the notice directly to the post.

![image](https://cloud.githubusercontent.com/assets/8368570/8866854/75a8c60a-318f-11e5-8fbb-6dfd7bddfb88.png)

Please excuse the rough sketch.

**Comment by bioshazard** [comment]
https://github.com/eflip/Blog/commit/9dc70fd7b3ac4111ed81b225e4e92d3ab26e387c
