### ISSUE TITLE
blog - Category count

### ISSUE THREAD

**Issue by wightmike** [eflip/Blog#9]
![image](https://cloud.githubusercontent.com/assets/8368570/8866663/fdbf569c-318c-11e5-9cd6-170b5beb8c1f.png)

The count is incorrect if you **change** the category of a post in the editor.

**Comment by apreichner** [comment]
You can fix this by changing the SELECT statement for categories in /blog/controller/blog.php. Currently, it is using "SELECT DISTINCT category FROM blog_threads", need to remove the DISTINCT so it no longer combines the categories.

**Comment by bioshazard** [comment]
I really need to make a separate categories table and quit being lazy trying push it all into one table.

**Comment by bioshazard** [comment]
not making a new table for now, just fixing the bug https://github.com/eflip/Blog/pull/14
